DROP TABLE IF EXISTS data CASCADE;

CREATE TABLE data (
    id SERIAL PRIMARY KEY NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    TEMP VARCHAR(30) NOT NULL,
    FEELLIKE VARCHAR(30) NOT NULL,
    WINDSPEED VARCHAR(30) NOT NULL,
    VISIBILITY VARCHAR(30) NOT NULL,
    STATUS VARCHAR(255) NOT NULL,
    DATE VARCHAR(255) NOT NULL
)   